### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by golamSaroar** [IonicaBizau/github-calendar#167]
I get the following error on the console:

```
TypeError: Failed to fetch 
    at f.proxy (github-calendar.min.js:35:18) 
    at f.getCalendar (github-calendar.min.js:41:21) 
    at l (github-calendar.min.js:45:20) 
    at t.exports (github-calendar.min.js:79:10) 
    at index.html:1073:7
```

**Comment by IonicaBizau** [comment]
This should be fixed now. 🎉
